replace getFirstAccountId
linagora/jmap-client-ts pull request #68
Opened 2022-06-29 04:22 UTC by qyb

for https://github.com/linagora/jmap-client-ts/issues/67

2022-06-29 04:28 UTC, chibenwa approved these changes

2022-06-30 07:36 UTC, alagane requested changes

2022-06-30 07:36 UTC, alagane commented on src/index.ts
> +    const primaryAccounts = this.session?.primaryAccounts;
```suggestion
    const primaryAccounts = this.getSession().primaryAccounts;
```
Here you can use the session getter to inform the user (throw an exception) if the session is not fetched yet.

2022-06-30 08:59 UTC, alagane approved these changes

2025-07-30 07:57 UTC, tttp commented
any progress here? @alagane you might want to get someone else reviewing, @chibenwa seems not the right person?

2025-07-30 09:32 UTC, fabienmoyon approved these changes

2025-07-31 20:31 UTC, chibenwa commented
Sorry this moved out of the radar.

Indeed we can move on with this change.

2025-07-31 20:31 UTC, merged